### ISSUE TITLE
Resurrecting this project

### ISSUE THREAD

**Issue by samprohaska** [fishtown-analytics/dbtdocs-to-lookml#1]
Hello!

I've been looking for a way to easily pass descriptions (and potentially more) from dbt -> looker, and this repo seems to do exactly that. I'm considering building this out further, but as it has been inactive for ~3 years, wanted to check in before moving forward.

Is there a tool that already accomplishes this? Any reasons not to pass descriptions from dbt -> looker? Anything else I should know?

Thanks!

**Comment by joshtemple** [comment]
Check out the dbt2looker project from the Lightdash team: https://github.com/lightdash/dbt2looker

**Comment by samprohaska** [comment]
excellent, thank you!
